#!/usr/bin/env python3
"""生成合成神经调质轨迹数据集 v6 (81 场景 + 4 维细化 + 精细强度, 可复用).

================================================================
数据集生成器 v6 (81 场景, 4 维细化, -50..+50 精细强度)
================================================================
4 个细化维度:
  1. 时间阶段划分: baseline → CS → US → recovery (不同阶段调质动态不同)
  2. 脑区特异性: VTA/striatum/PFC/amygdala/hippocampus/hypothalamus/insula
  3. 刺激强度梯度: -50 到 +50 整数 (101 档, scale = 1 + 0.02*i)
  4. 行为关联标注: approach/freezing/lever_press/exploration 等

81 个场景 (9 大类别):
  奖赏类 (8) / 应激类 (8) / 社交类 (10) / 认知类 (10)
  生理节律类 (10) / 情绪调节类 (4) / 学习记忆类 (3) / 基本情绪类 (1)
  病理类 (16, 默认禁用) / 治疗干预类 (6, 默认禁用)

权威神经科学规律:
  - FSCV 实测时间常数 (Kawagoe 1992, Deng 2024 等)
  - alpha 函数上升相 (Dayan & Abbott 2001)
  - Michaelis-Menten 摄取动力学 (Wightman 团队)
  - DA-5HT 拮抗耦合 (Daw 2002, Cools 2011)
  - 泊松过程 burst firing (DA 神经元 5-15 Hz burst)
  - 1/f 闪烁噪声 + 慢漂移 (路径 C, 模拟真实 GRAB 探针)
  - 对数正态峰值分布 (路径 D, Phillips 2003)

强度梯度系统 (-50 到 +50):
  scale = max(0.05, 1.0 + intensity * 0.02)
  -50 → 0.05 (最弱) | -25 → 0.50 (weak) | 0 → 1.00 (基准)
  +25 → 1.50 (strong) | +50 → 2.00 (最强)

用法:
    # 生成所有场景 (默认 intensity=0 基准)
    python generate_synthetic_grab_traces.py --preset all

    # 生成指定场景的全部 101 档强度
    python generate_synthetic_grab_traces.py --preset reward_anticipation --intensity all

    # 生成指定场景+指定强度
    python generate_synthetic_grab_traces.py --preset reward_anticipation --intensity 25

    # 范围+步长 (生成 -10 到 +10, 步长 5)
    python generate_synthetic_grab_traces.py --preset all --intensity -10:10:5

    # 逗号分隔多个强度
    python generate_synthetic_grab_traces.py --preset all --intensity -25,0,25

    # 兼容旧版命名
    python generate_synthetic_grab_traces.py --preset all --intensity medium

    # 自定义参数
    python generate_synthetic_grab_traces.py --preset all --duration 300 --seed 123

依赖:
    pip install numpy pyyaml
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import platform
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

try:
    import yaml
except ImportError:
    print("[ERROR] PyYAML 未安装, 请运行: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


# ============================================================================
# 版本与理论依据
# ============================================================================
DATASET_VERSION = "7.0.0"
THEORETICAL_BASIS = {
    "time_constants": {
        "source": "FSCV fast-scan cyclic voltammetry",
        "references": [
            "Kawagoe 1992 (PMID 1465186) - DA Michaelis-Menten kinetics",
            "Deng 2024 (PMID 38443508) - GRAB-5HT sensors",
            "Breton-Provencher 2022 (PMID 35650441) - NE looming response",
            "Jing 2020 - GRAB-ACh2.0 (AChE rapid degradation)",
            "Qian 2023 (PMID 36593404) - GRAB-Oxytocin",
            "Ford 2010 (PMID 20484639) - DA VTA vs striatum",
        ],
    },
    "alpha_function": {
        "source": "Computational neuroscience textbook (Dayan & Abbott 2001)",
        "description": "C(t) = A * (t/τ) * exp(1 - t/τ), standard synaptic response model",
    },
    "michaelis_menten": {
        "source": "Wightman team FSCV measurements",
        "description": "dC/dt = release(t) - V_max * C / (K_m + C), saturating uptake kinetics",
    },
    "da_5ht_coupling": {
        "source": "Daw 2002, Cools 2011",
        "description": "Reward (DA↑) inhibits punishment (5HT↓), opponent-process theory",
    },
    "poisson_burst": {
        "source": "DA neuron burst firing 5-15 Hz",
        "description": "Stimulus times generated by non-homogeneous Poisson process",
    },
    "brain_region_specificity": {
        "source": "Ford 2010 (PMID 20484639)",
        "description": "Same neurotransmitter has different kinetics in different brain regions (VTA vs striatum DA)",
    },
    "phase_structure": {
        "source": "Pavlovian conditioning paradigm (Schultz 1997)",
        "description": "baseline → CS (conditioned stimulus) → US (unconditioned stimulus) → recovery",
    },
}

CHANNELS = ["DA", "5HT", "NE", "ACh", "Oxy"]


# ============================================================================
# 核心数学模型
# ============================================================================
def alpha_rise(t_rel: np.ndarray, tau: float, peak: float) -> np.ndarray:
    """alpha 函数上升相."""
    sig = np.zeros_like(t_rel)
    mask = (t_rel >= 0) & (t_rel <= tau)
    x = t_rel[mask] / tau
    sig[mask] = peak * x * np.exp(1.0 - x)
    return sig


def generate_release_profile(t: np.ndarray, stim_time: float,
                              duration: float, peak: float,
                              rise_tau: float, stim_type: str,
                              v_max: float = 0.0, k_m: float = 0.0) -> np.ndarray:
    """生成单次刺激的释放速率剖面."""
    t_rel = t - stim_time
    release = np.zeros_like(t)

    if stim_type == "pulse":
        mask = (t_rel >= 0) & (t_rel <= rise_tau)
        x = t_rel[mask] / rise_tau
        release[mask] = (peak / rise_tau) * x * np.exp(1.0 - x)
    elif stim_type in ("plateau", "ramp"):
        if v_max > 0 and k_m > 0:
            release_rate = v_max * peak / (k_m + peak)
        else:
            release_rate = peak * 2.0
        rise_end = duration / 3.0
        plateau_end = 2.0 * duration / 3.0
        rise = (t_rel >= 0) & (t_rel <= rise_end)
        release[rise] = release_rate * (t_rel[rise] / rise_end)
        plateau = (t_rel > rise_end) & (t_rel <= plateau_end)
        release[plateau] = release_rate
        fall = (t_rel > plateau_end) & (t_rel <= duration)
        release[fall] = release_rate * (1.0 - (t_rel[fall] - plateau_end) / rise_end)
    return release


def poisson_stim_times(rate: float, duration: float, rng: np.random.Generator,
                        min_gap: float = 2.0) -> list[float]:
    """非齐次泊松过程生成刺激时间."""
    times = []
    t = 0.0
    while t < duration:
        gap = rng.exponential(1.0 / rate) if rate > 0 else duration
        t += gap
        if t >= duration:
            break
        if not times or (t - times[-1]) >= min_gap:
            times.append(t)
    return times


def simulate_concentration(release: np.ndarray, v_max: float, k_m: float,
                             dt: float, c_init: float = 0.0) -> np.ndarray:
    """Michaelis-Menten 数值积分."""
    n = len(release)
    conc = np.zeros(n, dtype=np.float64)
    conc[0] = c_init
    for i in range(1, n):
        uptake = v_max * conc[i-1] / (k_m + conc[i-1])
        conc[i] = conc[i-1] + (release[i] - uptake) * dt
        if conc[i] < 0:
            conc[i] = 0.0
    return conc


# ============================================================================
# 配置加载与合并
# ============================================================================
def load_config(config_path: Path) -> dict:
    with config_path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def get_phase_template(scenario_config: dict, config: dict) -> dict:
    """获取场景的阶段模板 (自定义或默认)."""
    template_name = scenario_config.get("phase_template", "default")
    return config["phase_templates"][template_name]


def get_brain_region_params(channel: str, brain_region: str,
                              base_params: dict, brain_regions: dict) -> dict:
    """合并基础参数 + 脑区特异性参数."""
    params = dict(base_params.get(channel, {}))
    region_params = brain_regions.get(brain_region, {}).get(channel, {})
    params.update(region_params)
    return params


def apply_intensity(params: dict, intensity,
                     intensity_levels: dict) -> dict:
    """应用强度梯度缩放.

    支持 -50 到 +50 的整数强度 (线性映射):
        scale = max(0.05, 1.0 + intensity * 0.02)
    兼容旧版 weak/medium/strong 字符串 (自动转换为 -25/0/+25).
    """
    # 兼容旧版字符串命名
    if isinstance(intensity, str):
        legacy_map = {"weak": -25, "medium": 0, "strong": 25}
        if intensity in legacy_map:
            intensity = legacy_map[intensity]
        else:
            # 尝试解析为整数
            try:
                intensity = int(intensity)
            except (ValueError, TypeError):
                intensity = 0

    # 线性映射: scale = max(0.05, 1.0 + intensity * 0.02)
    scale = max(0.05, 1.0 + intensity * 0.02)

    if intensity == 0:
        return params  # 基准无缩放

    result = dict(params)
    if "peak_df" in result:
        lo, hi = result["peak_df"]
        result["peak_df"] = [lo * scale, hi * scale]
    if "poisson_rate" in result:
        result["poisson_rate"] = result["poisson_rate"] * scale
    return result


def parse_intensity_arg(arg: str) -> list[int] | None:
    """解析强度命令行参数.

    支持格式:
        "all"              → -50 到 +50 全部 101 档
        "0"                → [0]
        "-10,0,10"         → [-10, 0, 10]
        "-10:10"           → [-10, -9, ..., 10] (步长 1)
        "-50:50:5"         → [-50, -45, ..., 50] (步长 5)
        "weak"             → [-25] (兼容旧版)
        "medium"           → [0] (兼容旧版)
        "strong"           → [25] (兼容旧版)

    返回: 整数列表, 或 None 表示解析失败.
    """
    arg = arg.strip()
    if not arg:
        return None

    # 兼容旧版命名
    legacy_map = {"weak": [-25], "medium": [0], "strong": [25]}
    if arg.lower() in legacy_map:
        return legacy_map[arg.lower()]

    # all: -50 到 +50 全部
    if arg.lower() == "all":
        return list(range(-50, 51))

    # 逗号分隔列表: -10,0,10
    if "," in arg:
        result = []
        for part in arg.split(","):
            part = part.strip()
            try:
                v = int(part)
                if not -50 <= v <= 50:
                    return None
                result.append(v)
            except ValueError:
                return None
        return result if result else None

    # 范围: START:END[:STEP]
    if ":" in arg:
        parts = arg.split(":")
        if len(parts) < 2 or len(parts) > 3:
            return None
        try:
            start = int(parts[0])
            end = int(parts[1])
            step = int(parts[2]) if len(parts) == 3 else 1
        except ValueError:
            return None
        if step <= 0:
            return None
        # 钳位到 [-50, 50]
        start = max(-50, min(50, start))
        end = max(-50, min(50, end))
        if start <= end:
            return list(range(start, end + 1, step))
        else:
            return list(range(start, end - 1, -step))

    # 单个整数
    try:
        v = int(arg)
        if not -50 <= v <= 50:
            return None
        return [v]
    except ValueError:
        return None


# ============================================================================
# 场景生成 (含阶段/脑区/强度/行为标注)
# ============================================================================
def generate_scenario(scenario_name: str, scenario_config: dict,
                       config: dict, output_root: Path, seed: int,
                       intensity = 0) -> dict:
    """生成单个场景的完整数据 (CSV + NPZ + events.json).

    支持 4 维细化:
    - 时间阶段: 刺激只在指定 phase 内出现
    - 脑区: 使用对应脑区的时间常数和摄取参数
    - 强度: -50..+50 整数 (线性映射 scale=1+0.02*i), 兼容 weak/medium/strong
    - 行为: 在 events.json 中输出 behavior 标注
    """
    global_config = config["global"]
    base_params = config["base_params"]
    brain_regions = config["brain_regions"]
    intensity_levels = config["intensity_levels"]
    phase_template = get_phase_template(scenario_config, config)

    duration = global_config["duration_s"]
    fs = global_config["fs_hz"]
    noise_scale = global_config.get("noise_std_scale", 1.0)
    da_5ht_coupling = global_config.get("da_5ht_coupling", 0.3)

    n_samples = int(duration * fs)
    t = np.linspace(0, duration, n_samples, dtype=np.float64)
    dt = float(t[1] - t[0])

    # 兼容旧版字符串强度 (weak/medium/strong → -25/0/+25)
    if isinstance(intensity, str):
        legacy_map = {"weak": -25, "medium": 0, "strong": 25}
        intensity = legacy_map.get(intensity, 0)

    # 强度归一化到整数 (支持浮点输入如 -25.5)
    intensity = int(round(intensity))

    # 场景种子 (场景名+强度联合哈希, 保证可复现且各版本独立)
    # 强度偏移: (intensity + 50) * 1000, 范围 [0, 100000], 保证非负且唯一
    #   intensity=-50 → offset=0, intensity=0 → offset=50000, intensity=+50 → offset=100000
    intensity_offset = (intensity + 50) * 1000
    scenario_seed = seed + hash(scenario_name) % 100000 + intensity_offset
    rng = np.random.default_rng(scenario_seed)

    # 输出目录: datasets/{scenario}/i{intensity:+03d}/
    # 命名: i-50, i-05, i+00, i+25, i+50 (补零对齐, 保证字典序)
    intensity_str = f"i{intensity:+03d}"
    scenario_dir = output_root / scenario_name / intensity_str
    csv_dir = scenario_dir / "csv"
    csv_dir.mkdir(parents=True, exist_ok=True)

    # 计算实际缩放因子 (用于日志和元数据)
    scale = max(0.05, 1.0 + intensity * 0.02)

    brain_region = scenario_config.get("brain_region", "PFC")
    behavior = scenario_config.get("behavior", "unknown")
    paradigm = scenario_config.get("paradigm", "unknown")

    print(f"\n[{scenario_name}/{intensity_str}] scale={scale:.2f} {scenario_config.get('description', '')[:40]}...")
    print(f"       brain={brain_region}, behavior={behavior}, seed={scenario_seed}")

    # 合并调质参数 (基础 + 脑区 + 场景覆盖 + 强度)
    modulators_config = scenario_config["modulators"]
    merged_params = {}
    for ch in CHANNELS:
        if ch not in modulators_config:
            continue
        base = get_brain_region_params(ch, brain_region, base_params, brain_regions)
        scene_override = modulators_config[ch]
        merged = {**base, **scene_override}
        merged = apply_intensity(merged, intensity, intensity_levels)
        merged_params[ch] = merged

    # 收集事件
    all_events = []
    concentrations = {}

    # 先生成 DA (用于 5HT 拮抗耦合)
    if "DA" in merged_params:
        da_sig, da_events = _generate_channel_with_phases(
            "DA", merged_params["DA"], t, rng, da_5ht_coupling,
            None, noise_scale, phase_template)
        concentrations["DA"] = da_sig.astype(np.float64)
        _save_csv(csv_dir / "DA.csv", t, da_sig)
        all_events.extend(da_events)

    # 生成 5HT (受 DA 拮抗)
    if "5HT" in merged_params:
        ht5_sig, ht5_events = _generate_channel_with_phases(
            "5HT", merged_params["5HT"], t, rng, da_5ht_coupling,
            concentrations.get("DA"), noise_scale, phase_template)
        concentrations["5HT"] = ht5_sig.astype(np.float64)
        _save_csv(csv_dir / "5HT.csv", t, ht5_sig)
        all_events.extend(ht5_events)

    # 生成 NE, ACh, Oxy
    for ch in ["NE", "ACh", "Oxy"]:
        if ch not in merged_params:
            continue
        sig, events = _generate_channel_with_phases(
            ch, merged_params[ch], t, rng, da_5ht_coupling,
            None, noise_scale, phase_template)
        concentrations[ch] = sig.astype(np.float64)
        _save_csv(csv_dir / f"{ch}.csv", t, sig)
        all_events.extend(events)

    # 保存 NPZ
    npz_path = scenario_dir / "traces.npz"
    np.savez_compressed(
        npz_path,
        time_s=t.astype(np.float32),
        **{ch: conc.astype(np.float32) for ch, conc in concentrations.items()},
        fs_hz=np.float32(fs),
        duration_s=np.float32(duration),
    )

    # 保存 events.json (含行为标注和阶段信息)
    events_data = {
        "scenario": scenario_name,
        "intensity": intensity,
        "intensity_str": intensity_str,
        "intensity_scale": float(scale),
        "description": scenario_config.get("description", ""),
        "paradigm": paradigm,
        "behavior": behavior,
        "brain_region": brain_region,
        "expected_state": scenario_config.get("expected_state", {}),
        "phases": phase_template,
        "n_events": len(all_events),
        "events": all_events,
    }
    events_path = scenario_dir / "events.json"
    with events_path.open("w", encoding="utf-8") as f:
        json.dump(events_data, f, indent=2, ensure_ascii=False)

    # 统计
    stats = {}
    for ch, conc in concentrations.items():
        stats[ch] = {
            "min": float(conc.min()),
            "max": float(conc.max()),
            "mean": float(conc.mean()),
        }

    for ch in CHANNELS:
        if ch in stats:
            s = stats[ch]
            n_ev = sum(1 for e in all_events if e["channel"] == ch)
            print(f"       {ch:4s}: min={s['min']:.3f} max={s['max']:.3f} "
                  f"mean={s['mean']:.3f} events={n_ev}")

    return {
        "scenario": scenario_name,
        "intensity": intensity,
        "intensity_str": intensity_str,
        "intensity_scale": float(scale),
        "description": scenario_config.get("description", ""),
        "paradigm": paradigm,
        "behavior": behavior,
        "brain_region": brain_region,
        "expected_state": scenario_config.get("expected_state", {}),
        "seed": scenario_seed,
        "n_events": len(all_events),
        "stats": stats,
        "files": {
            "csv_dir": str(csv_dir.relative_to(output_root.parent)),
            "traces_npz": str(npz_path.relative_to(output_root.parent)),
            "events_json": str(events_path.relative_to(output_root.parent)),
        },
    }


def _generate_channel_with_phases(channel: str, params: dict, t: np.ndarray,
                                    rng: np.random.Generator, da_5ht_coupling: float,
                                    da_conc: np.ndarray | None, noise_scale: float,
                                    phase_template: dict) -> tuple[np.ndarray, list]:
    """生成单通道轨迹, 刺激只在指定 phase 时间窗口内出现."""
    duration = float(t[-1])
    dt = float(t[1] - t[0]) if len(t) > 1 else 0.01

    # 获取该调质的目标 phase
    target_phase = params.get("phase", "CS")
    phase_info = phase_template.get(target_phase, {})
    phase_start = phase_info.get("start", 0)
    phase_duration = phase_info.get("duration", duration)
    phase_end = min(phase_start + phase_duration, duration)

    # 泊松过程生成刺激时间 (限制在 phase 时间窗口内)
    rate = params.get("poisson_rate", 0.05)
    stim_duration = params.get("stim_duration", 1.0)
    stim_times = poisson_stim_times(rate, phase_duration - stim_duration, rng,
                                      min_gap=stim_duration * 2.0)
    # 平移到 phase 起始时间
    stim_times = [st + phase_start for st in stim_times]
    if len(stim_times) < 2:
        n_fallback = max(3, int(phase_duration * rate))
        stim_times = list(np.linspace(phase_start + 0.1 * phase_duration,
                                        phase_end - 0.1 * phase_duration, n_fallback))

    # 累加释放速率
    total_release = np.zeros_like(t)
    events = []
    peak_lo, peak_hi = params.get("peak_df", [0.2, 0.4])

    # 路径 D: 对数正态峰值分布 (真实 DA 瞬态峰值呈右偏分布, Phillips 2003)
    # 将 [peak_lo, peak_hi] 转换为对数正态参数:
    #   均值 = (lo+hi)/2, 中位数略低于均值 (右偏)
    peak_mean = (peak_lo + peak_hi) * 0.5
    peak_std = (peak_hi - peak_lo) * 0.25  # 约 1/4 范围作为标准差
    # 防止 peak_mean <= 0 (低强度场景)
    if peak_mean <= 0.01:
        peak_mean = max(peak_mean, 0.02)
        peak_std = max(peak_std, 0.005)
    # 对数正态参数: mu = ln(mean^2 / sqrt(mean^2 + std^2))
    #                sigma = sqrt(ln(1 + std^2/mean^2))
    var_plus_mean2 = peak_mean * peak_mean + peak_std * peak_std
    log_mu = np.log(peak_mean * peak_mean / np.sqrt(var_plus_mean2))
    log_sigma = np.sqrt(np.log(var_plus_mean2 / (peak_mean * peak_mean)))

    for stim_t in stim_times:
        # 对数正态采样, 钳位到 [peak_lo*0.3, peak_hi*1.5] 防极端值
        peak = float(rng.lognormal(log_mu, log_sigma))
        peak = max(peak_lo * 0.3, min(peak_hi * 1.5, peak))

        # DA-5HT 拮抗耦合
        coupling_applied = 0.0
        if channel == "5HT" and da_conc is not None:
            stim_idx = min(int(np.searchsorted(t, stim_t)), len(da_conc) - 1)
            da_at_stim = da_conc[stim_idx]
            inhibition = da_5ht_coupling * min(da_at_stim, 1.0)
            coupling_applied = inhibition
            peak = peak * (1.0 - inhibition)

        rel = generate_release_profile(
            t, stim_t, stim_duration, peak,
            params["rise_tau"], params["stim_type"],
            params.get("v_max", 1.0), params.get("k_m", 0.3))
        total_release += rel

        events.append({
            "channel": channel,
            "time_s": float(stim_t),
            "peak_target": float(peak),
            "stim_type": params["stim_type"],
            "stim_duration_s": float(stim_duration),
            "phase": target_phase,
            "da_5ht_coupling_applied": float(coupling_applied),
            "peak_distribution": "lognormal",
        })

    # Michaelis-Menten 积分
    conc = simulate_concentration(total_release,
                                    params.get("v_max", 1.0),
                                    params.get("k_m", 0.3), dt)

    # 路径 C: 1/f 闪烁噪声 + 慢漂移 (替代高斯白噪声)
    # 真实 GRAB 信号噪声谱: 1/f (低频强, 高频弱) + 慢漂移 (< 0.1Hz)
    # 来源: GRAB 探针光漂白 + 血流信号 + 呼吸节律
    noise_std = params["noise_std"] * noise_scale
    noise = _generate_realistic_noise(len(t), noise_std, rng)

    # 基线 + 真实噪声
    df_f = conc.astype(np.float32)
    df_f += params.get("baseline", 0.0)
    df_f += noise.astype(np.float32)
    df_f = np.clip(df_f, 0.0, 1.5)

    return df_f, events


def _generate_realistic_noise(n: int, sigma: float,
                                rng: np.random.Generator) -> np.ndarray:
    """生成 1/f 闪烁噪声 + 慢漂移 + 高频白噪声 (模拟真实 GRAB 信号).

    真实 GRAB 探针信号的噪声组成:
      1. 1/f 闪烁噪声 (光漂白 + 探测器噪声, 低频强)
      2. 慢漂移 (血流/呼吸节律, < 0.1 Hz)
      3. 高频白噪声 (读出噪声)

    实现: 频域 1/f 滤波 + 正弦慢漂移叠加.
    """
    if n < 4 or sigma <= 0:
        return np.zeros(n, dtype=np.float32)

    # 1. 1/f 闪烁噪声: 频域生成
    # 白噪声 → FFT → 乘 1/sqrt(f) → IFFT
    white = rng.standard_normal(n).astype(np.float64)
    fft = np.fft.rfft(white)
    freqs = np.fft.rfftfreq(n)
    # 避免除零, freqs[0]=0 时保持原值 (DC 分量)
    freqs[0] = 1.0
    # 1/f 滤波: 振幅 ∝ 1/sqrt(f)
    spectrum = fft / np.sqrt(np.abs(freqs))
    # 恢复 DC 分量为 0 (避免常数偏移)
    spectrum[0] = 0.0
    flicker = np.fft.irfft(spectrum, n=n)
    # 归一化到目标标准差
    flicker_std = flicker.std()
    if flicker_std > 1e-10:
        flicker = flicker / flicker_std * sigma * 0.6  # 60% 来自 1/f

    # 2. 慢漂移: 0.02-0.1 Hz 正弦混合 (模拟呼吸 + 血流)
    t_idx = np.arange(n, dtype=np.float64)
    drift_freqs = rng.uniform(0.02, 0.10, size=2)  # 2 个随机低频
    drift_phases = rng.uniform(0, 2 * np.pi, size=2)
    drift = np.zeros(n, dtype=np.float64)
    for f, p in zip(drift_freqs, drift_phases):
        drift += np.sin(2 * np.pi * f * t_idx / n + p)
    # 漂移幅度: sigma * 0.3 (30% 来自慢漂移)
    drift = drift / drift.std() * sigma * 0.3 if drift.std() > 1e-10 else drift

    # 3. 高频白噪声: 10% (少量读出噪声)
    white_high = rng.standard_normal(n).astype(np.float64) * sigma * 0.1

    noise = flicker + drift + white_high
    return noise


def _save_csv(path: Path, time_s: np.ndarray, df_f: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["time_s", "dF_F"])
        for t_val, v in zip(time_s, df_f):
            writer.writerow([f"{t_val:.4f}", f"{v:.6f}"])


# ============================================================================
# Manifest
# ============================================================================
def compute_config_hash(config: dict) -> str:
    config_str = json.dumps(config, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(config_str.encode("utf-8")).hexdigest()


def generate_manifest(output_root: Path, config: dict, scenarios_meta: list,
                       config_path: Path, args) -> Path:
    manifest = {
        "dataset_version": DATASET_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": {
            "script": "generate_synthetic_grab_traces.py",
            "python_version": platform.python_version(),
            "numpy_version": np.__version__,
            "platform": platform.platform(),
        },
        "config": {
            "source_file": str(config_path.name),
            "config_hash_sha256": compute_config_hash(config),
            "global": config["global"],
        },
        "generation_args": {
            "presets": args.preset,
            "intensities": args.intensity,
            "duration_s": args.duration,
            "fs_hz": args.fs,
            "seed": args.seed,
        },
        "theoretical_basis": THEORETICAL_BASIS,
        "scenarios": scenarios_meta,
        "directory_structure": {
            "{scenario}/i{N:+03d}/csv/": "WebPlotDigitizer 兼容 CSV (N=-50..+50)",
            "{scenario}/i{N:+03d}/traces.npz": "标准化张量 (SNN 输入)",
            "{scenario}/i{N:+03d}/events.json": "事件标注 + 行为/阶段信息",
        },
        "refinement_dimensions": {
            "phases": "baseline → CS → US → recovery",
            "brain_regions": list(config["brain_regions"].keys()),
            "intensity_system": {
                "mode": "linear_integer",
                "range": [-50, 50],
                "formula": "scale = max(0.05, 1.0 + intensity * 0.02)",
                "n_levels": 101,
                "legacy_mapping": {"weak": -25, "medium": 0, "strong": 25},
            },
            "behavior_annotations": "每个场景附带对应行为输出标注",
        },
    }

    manifest_path = output_root / "manifest.json"
    with manifest_path.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    return manifest_path


def save_config_snapshot(config: dict, output_root: Path) -> Path:
    snapshot_path = output_root / "config_snapshot.yaml"
    with snapshot_path.open("w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return snapshot_path


# ============================================================================
# 主函数
# ============================================================================
def get_category_map(config: dict) -> dict:
    """从 YAML 的 categories 字段动态构建分类映射 (支持新增类别)."""
    return config.get("categories", {})


def filter_enabled_presets(preset_names: list, config: dict,
                            include_disabled: bool) -> tuple[list, list]:
    """根据 enabled 标志过滤场景.

    返回: (启用场景列表, 跳过的禁用场景列表)
    病理类场景默认 enabled: false, 需 --include-disabled 显式启用.
    """
    enabled, skipped = [], []
    for name in preset_names:
        scene = config["presets"].get(name, {})
        is_enabled = scene.get("enabled", True)
        if is_enabled or include_disabled:
            enabled.append(name)
        else:
            skipped.append(name)
    return enabled, skipped


def main() -> int:
    parser = argparse.ArgumentParser(
        description="生成合成神经调质轨迹数据集 v4 (多场景, 4 维细化, 病理类开关)."
    )
    parser.add_argument(
        "--preset", default="all",
        help="场景预设: all | 类别名(奖赏类/应激类/...) | 具体场景名 (逗号分隔)",
    )
    parser.add_argument(
        "--intensity", default="0",
        help="强度梯度 (-50 到 +50 整数): all | N | N1,N2,N3 | START:END[:STEP] (默认 0)",
    )
    parser.add_argument(
        "--config", default="src/snn/tools/traces_config.yaml",
        help="YAML 配置文件路径",
    )
    parser.add_argument(
        "--output-dir", default="data/neuroscience_traces/datasets",
        help="数据集输出根目录",
    )
    parser.add_argument("--duration", type=float, default=None, help="覆盖配置中的轨迹时长 (秒)")
    parser.add_argument("--fs", type=float, default=None, help="覆盖配置中的采样率 (Hz)")
    parser.add_argument("--seed", type=int, default=42, help="随机种子 (默认 42)")
    parser.add_argument("--list-presets", action="store_true", help="列出所有可用场景预设")
    parser.add_argument(
        "--include-disabled", action="store_true",
        help="强制启用被标记为 enabled:false 的场景 (默认跳过病理类)",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"[ERROR] 配置文件不存在: {config_path}", file=sys.stderr)
        return 1
    config = load_config(config_path)

    if args.duration is not None:
        config["global"]["duration_s"] = args.duration
    if args.fs is not None:
        config["global"]["fs_hz"] = args.fs

    categories = get_category_map(config)

    if args.list_presets:
        total = len(config["presets"])
        n_enabled = sum(1 for s in config["presets"].values()
                        if s.get("enabled", True))
        n_disabled = total - n_enabled
        print(f"可用场景预设 (共 {total} 个, 启用 {n_enabled}, 禁用 {n_disabled}):")
        for cat, names in categories.items():
            print(f"\n  [{cat}] ({len(names)} 个)")
            for name in names:
                scene = config["presets"].get(name, {})
                desc = scene.get("description", "")[:50]
                flag = "" if scene.get("enabled", True) else " [DISABLED]"
                print(f"    {name:35s} - {desc}{flag}")
        print("\n强度梯度: -50 到 +50 整数 (scale = 1 + 0.02*i)")
        print("  示例: --intensity 0 | -10,0,10 | -10:10 | -50:50:5 | all")
        print("  兼容: weak(-25) | medium(0) | strong(25)")
        print("提示: 禁用场景需 --include-disabled 才生成")
        return 0

    # 解析预设
    if args.preset.lower() == "all":
        preset_names = list(config["presets"].keys())
    elif args.preset in categories:
        preset_names = categories[args.preset]
    else:
        preset_names = [p.strip() for p in args.preset.split(",")]
        for name in preset_names:
            if name not in config["presets"]:
                print(f"[ERROR] 未知预设: {name}", file=sys.stderr)
                print(f"        可用: {', '.join(config['presets'].keys())}", file=sys.stderr)
                return 1

    # 根据 enabled 标志过滤
    preset_names, skipped = filter_enabled_presets(
        preset_names, config, args.include_disabled)

    if skipped and not args.include_disabled:
        print(f"[INFO] 跳过 {len(skipped)} 个禁用场景 (病理类, 使用 --include-disabled 启用):")
        for name in skipped:
            print(f"       - {name}")

    if not preset_names:
        print("[WARN] 没有启用的场景可生成. 使用 --include-disabled 启用病理类场景.")
        return 0

    # 解析强度 (-50 到 +50 整数)
    intensities = parse_intensity_arg(args.intensity)
    if intensities is None:
        print(f"[ERROR] 无效的强度参数: {args.intensity}", file=sys.stderr)
        print("       支持格式: all | N | N1,N2,N3 | START:END | START:END:STEP", file=sys.stderr)
        print("       范围: -50 到 +50", file=sys.stderr)
        return 1

    output_root = Path(args.output_dir)
    output_root.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] 生成神经调质轨迹数据集 v{DATASET_VERSION}")
    print(f"       输出: {output_root}")
    print(f"       启用场景: {len(preset_names)}, 跳过: {len(skipped)}, 强度档: {len(intensities)}")
    print(f"       总子数据集: {len(preset_names) * len(intensities)}")
    print(f"       时长: {config['global']['duration_s']}s, "
          f"采样率: {config['global']['fs_hz']}Hz, 种子: {args.seed}")

    snapshot_path = save_config_snapshot(config, output_root)
    print(f"\n[OK] 配置快照: {snapshot_path}")

    # 生成所有场景 × 强度
    scenarios_meta = []
    start_time = time.time()
    for name in preset_names:
        for intensity in intensities:
            meta = generate_scenario(
                name, config["presets"][name], config,
                output_root, args.seed, intensity)
            scenarios_meta.append(meta)

    elapsed = time.time() - start_time
    manifest_path = generate_manifest(output_root, config, scenarios_meta, config_path, args)

    print(f"\n[OK] Manifest: {manifest_path}")
    print(f"\n{'='*70}")
    print(f"[DONE] 数据集生成完成")
    print(f"       启用场景: {len(preset_names)}")
    print(f"       强度档: {len(intensities)}")
    print(f"       总子数据集: {len(scenarios_meta)}")
    print(f"       总事件数: {sum(s['n_events'] for s in scenarios_meta)}")
    print(f"       耗时: {elapsed:.2f}s")
    print(f"       配置 SHA256: {compute_config_hash(config)[:16]}...")
    print(f"       可复现: 相同配置 + seed={args.seed} → 完全相同数据集")
    print(f"{'='*70}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
